### ISSUE TITLE
Dev install doesn't work without h5py already installed

### ISSUE THREAD

**Issue by saulshanabrook** [telamonian/jupyterlab-hdf#5]
```
pip install -e .
Obtaining file:///Users/saul/p/jupyterlab-hdf
    ERROR: Command errored out with exit status 1:
     command: /usr/local/miniconda3/envs/jupyterlab-hdf/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/saul/p/jupyterlab-hdf/setup.py'"'"'; __file__='"'"'/Users/saul/p/jupyterlab-hdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /Users/saul/p/jupyterlab-hdf/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/saul/p/jupyterlab-hdf/setup.py", line 56, in <module>
        from jupyterlab_hdf._version import __version__
      File "/Users/saul/p/jupyterlab-hdf/jupyterlab_hdf/__init__.py", line 10, in <module>
        from .contents import HdfContentsManager, HdfContentsHandler
      File "/Users/saul/p/jupyterlab-hdf/jupyterlab_hdf/contents.py", line 7, in <module>
        import h5py
    ModuleNotFoundError: No module named 'h5py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

You are using option 6 [here](https://packaging.python.org/guides/single-sourcing-package-version/), which comes with this warning:

> Although this technique is common, beware that it will fail if sample/__init__.py imports packages from install_requires dependencies, which will very likely not be installed yet when setup.py is run.

**Comment by telamonian** [comment]
Hmm, I see the problem. Are you prepping a PR? If not I'll just fix it

**Comment by saulshanabrook** [comment]
>  Hmm, I see the problem. Are you prepping a PR? If not I'll just fix it

Nope, I worked around it by installing h5py first

**Comment by telamonian** [comment]
Makes sense. Think I'll choose option 1, then

**Comment by telamonian** [comment]
Ended up going with option 3, since that was already built into my `setupbase.py` file
